# Generated by Django 5.2.12 on 2026-03-22 04:53

import django.core.validators
import promocode.models
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DiscountPromoCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=50, unique=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "valid_until",
                    models.DateTimeField(default=promocode.models.default_valid_until),
                ),
                (
                    "max_usages",
                    models.IntegerField(
                        default=1,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "discount_percent",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(100),
                        ]
                    ),
                ),
                (
                    "allowed_category",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("another", "Another"),
                            ("game", "Game"),
                            ("skin", "Skin"),
                            ("vpn", "Vpn"),
                            ("subscription", "Subscription"),
                        ],
                        default=None,
                        null=True,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
