# Generated by Django 5.2.12 on 2026-03-22 04:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Good",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "count",
                    models.IntegerField(
                        default=1,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("another", "Another"),
                            ("game", "Game"),
                            ("skin", "Skin"),
                            ("vpn", "Vpn"),
                            ("subscription", "Subscription"),
                        ],
                        default="another",
                        max_length=50,
                    ),
                ),
            ],
        ),
    ]
