# Generated by Django 5.2.12 on 2026-03-22 15:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("goods", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="good",
            name="promo_eligible",
            field=models.BooleanField(default=True),
        ),
    ]
